name: enterprise plugins tests workflow

on:
  workflow_call:
    inputs:
      esdb_version:
        required: true
        type: string

jobs:
  single_node:
    name: Single Node

    strategy:
      fail-fast: false
      matrix:
        test: [ Plugins ]

    runs-on: ubuntu-latest
    steps:
      - name: Login to Cloudsmith
        uses: docker/login-action@v3
        with:
          registry: docker.eventstore.com
          username: ${{ secrets.CLOUDSMITH_CICD_USER }}
          password: ${{ secrets.CLOUDSMITH_CICD_TOKEN }}

      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4

      - name: Generate certificates
        run: |
          docker compose --file configure-tls-for-tests.yml up
          docker compose --file configure-user-certs-for-tests.yml up

      - name: Execute Gradle build
        run: ./gradlew ci --tests ${{ matrix.test }}Tests
        env:
          EVENTSTORE_DOCKER_REGISTRY_ENV: docker.eventstore.com
          EVENTSTORE_DOCKER_IMAGE_ENV: eventstore-ee/eventstoredb-commercial
          EVENTSTORE_DOCKER_TAG_ENV: ${{ inputs.esdb_version }}
          SECURE: true

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: esdb_logs.tar.gz
          path: db-client-java/esdb_logs.tar.gz
          if-no-files-found: error

  cluster:
    name: Cluster

    strategy:
      fail-fast: false
      matrix:
        test: [ Plugins ]

    runs-on: ubuntu-latest
    steps:
      - name: Login to Cloudsmith
        uses: docker/login-action@v3
        with:
          registry: docker.eventstore.com
          username: ${{ secrets.CLOUDSMITH_CICD_USER }}
          password: ${{ secrets.CLOUDSMITH_CICD_TOKEN }}

      - uses: actions/checkout@v3

      - name: Enable plugins
        run: echo "EventStore__Plugins__UserCertificates__Enabled=true" >> vars.env

      - name: Set up cluster with Docker Compose
        run: docker compose up -d
        env:
          CONTAINER_REGISTRY: docker.eventstore.com
          CONTAINER_IMAGE: eventstore-ee/eventstoredb-commercial
          CONTAINER_IMAGE_VERSION: ${{ inputs.esdb_version }}

      - name: Generate user certificates
        run: docker compose --file configure-user-certs-for-tests.yml up

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4

      - name: Execute Gradle build
        run: ./gradlew ci --tests ${{ matrix.test }}Tests
        env:
          SECURE: true
          CLUSTER: true

      - name: Shutdown cluster
        run: docker compose down