name: tests workflow

on:
  workflow_call:
    inputs:
      runtime_env:
        type: string
        default: release

      esdb_version:
        required: true
        type: string

jobs:
  provide_docker:
    uses: ./.github/workflows/docker-repo.yml
    with:
      runtime_env: ${{ inputs.runtime_env }}

  single_node:
    needs: provide_docker
    name: Single node

    strategy:
      fail-fast: false
      matrix:
        test: [Streams, PersistentSubscriptions, Telemetry]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4

      - name: Execute Gradle build
        run: ./gradlew ci --tests ${{ matrix.test }}Tests
        env:
          EVENTSTORE_DOCKER_REGISTRY_ENV: docker.eventstore.com
          EVENTSTORE_DOCKER_IMAGE_ENV: ${{ needs.provide_docker.outputs.docker_repo }}/${{ needs.provide_docker.outputs.docker_container }}
          EVENTSTORE_DOCKER_TAG_ENV: ${{ inputs.esdb_version }}

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: esdb_logs.tar.gz
          path: /tmp/esdb_logs.tar.gz
          if-no-files-found: error

  secure:
    needs: provide_docker
    name: Secure

    strategy:
      fail-fast: false
      matrix:
        test: [Streams, PersistentSubscriptions]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate certificates
        run: docker compose --file configure-tls-for-tests.yml up

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4

      - name: Execute Gradle build
        run: ./gradlew ci --tests ${{ matrix.test }}Tests
        env:
          EVENTSTORE_DOCKER_REGISTRY_ENV: docker.eventstore.com
          EVENTSTORE_DOCKER_IMAGE_ENV: ${{ needs.provide_docker.outputs.docker_repo }}/${{ needs.provide_docker.outputs.docker_container }}
          EVENTSTORE_DOCKER_TAG_ENV: ${{ inputs.esdb_version }}
          SECURE: true

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: esdb_logs.tar.gz
          path: /tmp/esdb_logs.tar.gz

  cluster:
    needs: provide_docker
    name: Cluster

    strategy:
      fail-fast: false
      matrix:
        test: [Streams, PersistentSubscriptions]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up cluster with Docker Compose
        run: docker compose up -d
        env:
          CONTAINER_REGISTRY: docker.eventstore.com
          CONTAINER_IMAGE: ${{ needs.provide_docker.outputs.docker_repo }}/${{ needs.provide_docker.outputs.docker_container }}
          CONTAINER_IMAGE_VERSION: ${{ inputs.esdb_version }}

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4

      - name: Execute Gradle build
        run: ./gradlew ci --tests ${{ matrix.test }}Tests
        env:
          CLUSTER: true
          SECURE: true

      - name: Shutdown cluster
        run: docker compose down